export { createJsonSchemaAdapter } from './adapter.js'
export { ProjectionValidationDivergenceError } from './projection-validation-coherence.js'
export type { AdapterConfig } from './types.js'
export type { SchemaResourceResolver } from './resources.js'
export { SchemaResourceResolutionError } from './resources.js'
export type { Dialect } from './dialect.js'
export { ProjectionMarkerCollisionError, SameLocationCycleError } from './schema-graph.js'
